image: node:14.16.0

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - node
          script:
            - npm install
            - npm run build
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm run build